#!/usr/bin/env node

import { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const program = new Command();

program
  .name('proces')
  .description('CLI for Sales Room (Proces OS) - Discovery analysis and Battlecard generation')
  .version('0.1.0');

// Analyze command - Discovery Insight Extractor
program
  .command('analyze <file>')
  .description('Analyze a meeting transcript and extract insights using Nessencja/Proces framework')
  .option('-o, --output <format>', 'Output format: md, json', 'md')
  .option('-d, --deal <dealId>', 'Link to existing deal')
  .action(async (file, options) => {
    const spinner = ora('Analyzing transcript...').start();

    try {
      // Check if file exists
      const filePath = path.resolve(process.cwd(), file);
      if (!fs.existsSync(filePath)) {
        spinner.fail(chalk.red(`File not found: ${file}`));
        process.exit(1);
      }

      // Read file content
      const content = fs.readFileSync(filePath, 'utf-8');
      spinner.text = 'Processing transcript content...';

      // TODO: Call AI API to extract insights
      // For now, show placeholder output
      spinner.succeed(chalk.green('Transcript analyzed successfully!'));

      console.log('\n' + chalk.bold.blue('═══════════════════════════════════════════════════'));
      console.log(chalk.bold.white('  DISCOVERY INSIGHTS - Nessencja/Proces Framework'));
      console.log(chalk.bold.blue('═══════════════════════════════════════════════════\n'));

      console.log(chalk.bold.yellow('📋 PAIN POINTS (Business Problems)'));
      console.log(chalk.gray('─────────────────────────────────────'));
      console.log('• [Pain points will be extracted by AI]');
      console.log('');

      console.log(chalk.bold.cyan('👥 STAKEHOLDER MAP'));
      console.log(chalk.gray('─────────────────────────────────────'));
      console.log('| Name | Title | Role |');
      console.log('|------|-------|------|');
      console.log('| [To be extracted] | | |');
      console.log('');

      console.log(chalk.bold.red('🚩 RED FLAGS'));
      console.log(chalk.gray('─────────────────────────────────────'));
      console.log('• [Red flags will be extracted by AI]');
      console.log('');

      console.log(chalk.bold.green('✅ NEXT STEPS'));
      console.log(chalk.gray('─────────────────────────────────────'));
      console.log('1. [Next steps will be generated by AI]');
      console.log('');

      console.log(chalk.gray('\nCopy this output to your CRM or notes.'));
      console.log(chalk.gray('For full analysis, use the web UI at http://localhost:5173/discovery\n'));

    } catch (error) {
      spinner.fail(chalk.red(`Error: ${error.message}`));
      process.exit(1);
    }
  });

// Battle command - Objection Battlecard Generator
program
  .command('battle [type]')
  .description('Generate quick battlecard response for objection type')
  .option('-e, --email', 'Generate detailed email response instead of bullets')
  .action(async (type, options) => {
    const validTypes = ['price', 'technology', 'trust', 'competition', 'timing', 'features'];

    if (type && !validTypes.includes(type.toLowerCase())) {
      console.log(chalk.red(`Invalid objection type: ${type}`));
      console.log(chalk.gray(`Valid types: ${validTypes.join(', ')}`));
      process.exit(1);
    }

    const spinner = ora('Generating battlecard response...').start();

    try {
      // TODO: Call AI API to generate response
      await new Promise(resolve => setTimeout(resolve, 500)); // Simulate API call

      spinner.succeed(chalk.green('Battlecard generated!'));

      console.log('\n' + chalk.bold.blue('═══════════════════════════════════════════════════'));
      console.log(chalk.bold.white(`  BATTLECARD: ${(type || 'General').toUpperCase()} OBJECTION`));
      console.log(chalk.bold.blue('═══════════════════════════════════════════════════\n'));

      if (options.email) {
        console.log(chalk.bold.yellow('📧 Detailed Email Response (ARC Framework)\n'));
        console.log(chalk.bold('Acknowledge:'));
        console.log('"I completely understand your concern about [objection]. Many of our clients initially felt the same way..."\n');
        console.log(chalk.bold('Reframe:'));
        console.log('"However, when we look at the total cost of ownership and the ROI our clients typically see..."\n');
        console.log(chalk.bold('Counter:'));
        console.log('"In fact, [Client X] saw a 40% reduction in costs within 6 months. I\'d love to share their case study with you."\n');
      } else {
        console.log(chalk.bold.yellow('⚡ Quick Response Bullets:\n'));
        console.log(chalk.white('• "I hear you - let me address that directly..."'));
        console.log(chalk.white('• "Many clients had the same concern before seeing ROI of X%..."'));
        console.log(chalk.white('• "Would it help if I shared how [Similar Company] handled this?"'));
        console.log('');
      }

      console.log(chalk.gray('For more responses, visit http://localhost:5173/battlecards\n'));

    } catch (error) {
      spinner.fail(chalk.red(`Error: ${error.message}`));
      process.exit(1);
    }
  });

// Search command - Intent Scraper (start a search)
program
  .command('search <objective>')
  .description('Start an Intent Scraper search (runs in background)')
  .option('-t, --template <id>', 'Use ICP template')
  .action(async (objective, options) => {
    const spinner = ora('Starting search...').start();

    try {
      // TODO: Call API to start background search
      await new Promise(resolve => setTimeout(resolve, 500));

      spinner.succeed(chalk.green('Search queued successfully!'));
      console.log(chalk.gray('\nSearch is running in the background.'));
      console.log(chalk.gray('You will be notified via Slack when results are ready.'));
      console.log(chalk.gray('View results at http://localhost:5173/intent-scraper\n'));

    } catch (error) {
      spinner.fail(chalk.red(`Error: ${error.message}`));
      process.exit(1);
    }
  });

// Status command - Check deal health
program
  .command('status [dealId]')
  .description('Check deal status and health score')
  .action(async (dealId) => {
    const spinner = ora('Fetching deal status...').start();

    try {
      // TODO: Call API to get deal status
      await new Promise(resolve => setTimeout(resolve, 300));

      spinner.succeed(chalk.green('Status retrieved!'));

      if (dealId) {
        console.log('\n' + chalk.bold.blue(`Deal: ${dealId}`));
        console.log(chalk.gray('─────────────────────────────────────'));
        console.log(`Stage: ${chalk.yellow('Discovery')}`);
        console.log(`Health Score: ${chalk.green('75%')}`);
        console.log(`Next Step: ${chalk.white('Follow-up call scheduled')}`);
        console.log(`Due: ${chalk.yellow('Tomorrow')}`);
      } else {
        console.log('\n' + chalk.bold.blue('Pipeline Overview'));
        console.log(chalk.gray('─────────────────────────────────────'));
        console.log('For detailed pipeline view, visit http://localhost:5173/deals\n');
      }

    } catch (error) {
      spinner.fail(chalk.red(`Error: ${error.message}`));
      process.exit(1);
    }
  });

program.parse();
